name: alloy
services:
  alloy:
    volumes:
      - /home/csh0101/lab/netagent/optl/alloy.config:/etc/alloy/config.alloy
    ports:
      - 12345:12345
    image: grafana/alloy:latest
    command: run --server.http.listen-addr=0.0.0.0:12345
      --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
  pyroscope:
    ports:
      - 4040:4040
    image: grafana/pyroscope
